
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ID = 6;
  public static final int COMMA = 2;
  public static final int error = 1;
  public static final int SEMI = 3;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int INT = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "SEMI",
  "INT",
  "FLOAT",
  "ID"
  };
}

